apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  labels:
    app: node-api-service
    tier: front
spec:
  selector:
    app: node-api
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
