apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-gitops-blue-green-staging
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: demo-node-api
  source:
    path: apps/node-demo/staging
    repoURL: git@github.com:mtyiska/argo_gitops_blue_green.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
