apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ingress.yaml
- rollout.yaml
patches:
- path: service.yaml               # Override for NodePort
- path: preview-service.yaml 
namespace: staging
commonAnnotations:
  supported-by: sre@example.com
labels:
- includeSelectors: false
  pairs:
    project: instanode-api
images:
- name: measureapp/demo-node-api
  newName: measureapp/demo-node-api
  newTag: 0.0.1
